[package]
name = "insula"
version = "0.0.1"
authors = ["Lucian Petrut <lpetrut@cloudbasesolutions.com>"]


[dependencies]
libc = "*"
libkvm = "0.0.1"

[patch.crates-io]
libkvm = { path = "../libkvm" }

